# Generated by Django 3.1.7 on 2021-05-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kraj', models.CharField(max_length=50)),
                ('miasto', models.CharField(max_length=50)),
                ('ulica', models.CharField(max_length=50)),
                ('nr_domu', models.CharField(max_length=10)),
                ('kod_pocz', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sprzet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('nazwa', models.CharField(max_length=50)),
                ('ilosc', models.IntegerField()),
                ('cena', models.FloatField(max_length=10)),
                ('kategoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('adres', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wypozyczalnia.adres')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('nr_tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('adres', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wypozyczalnia.adres')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('nr_tel', models.CharField(max_length=20)),
                ('zarobki', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczalnia',
            fields=[
                ('adres', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wypozyczalnia.adres')),
                ('nazwa', models.CharField(max_length=100)),
                ('nr_tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Promocja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rozpoczecia', models.DateTimeField()),
                ('data_zakonczenia', models.DateTimeField()),
                ('sprzet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.sprzet')),
            ],
        ),
        migrations.CreateModel(
            name='Naprawa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('data_zgloszenia', models.DateTimeField()),
                ('czy_naprawione', models.BooleanField()),
                ('data_naprawy', models.DateTimeField()),
                ('sprzet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.sprzet')),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wydania', models.DateTimeField()),
                ('data_zwrotu', models.DateTimeField()),
                ('sprzet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.sprzet')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.klient')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.pracownik')),
            ],
        ),
        migrations.AddField(
            model_name='sprzet',
            name='wypozyczalnia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.wypozyczalnia'),
        ),
    ]
