# Generated by Django 3.1.7 on 2021-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocja',
            name='data_rozpoczecia',
            field=models.DateTimeField(default=0),
        ),
    ]
